name: Latest blog post workflow
on:
  workflow_dispatch: # Manual dispatch
  schedule: # Run workflow automatically
    - cron: '0 1 * * 0' # At 1:00 on Sunday

jobs:
  get-posts:
    name: Get posts from RSS feed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull into readme
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://eddiequinn.xyz/index.xml"
          max_post_count: 10
          readme_path: README.md
          gh_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit_message: 'chore: Updated recent blog posts (short)'
      - name: pull into blogposts
        uses: gautamkrishnar/blog-post-workflow@v1
          with:
          feed_list: "https://eddiequinn.xyz/index.xml"
          max_post_count: 100
          readme_path: BLOG-POSTS.md
          gh_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit_message: 'chore: Updated recent blog posts (long)'

